import { useState, type ReactNode } from 'react'
import { AlertTriangle, BarChart3, CalendarDays, CheckCircle2, FileText, Mail, Sparkles, UserRoundCheck } from 'lucide-react'
import { assistantQuestions, demoActions, demoAlerts, demoKpis, milestones, permitRows, responsibilityLoad, riskDistribution, statusDistribution } from '../../data/dashboardDemo'
const labels = ['Proyecto','Permiso','Estado','Avance','Riesgo','Días','Pendiente','Responsable']
export function DashboardDemo({ active }: { active: string }) {
  if (active === 'portafolio') return <PortfolioOverview />
  if (active === 'alertas') return <Panel title="Alertas que requieren atención" icon={<AlertTriangle/>}><AlertPanel limit={3}/></Panel>
  if (active === 'permisos') return <Panel title="Registro ejecutivo de permisos" icon={<BarChart3/>}><PermitRegister /></Panel>
  if (active === 'hitos') return <Panel title="Agenda de hitos y vencimientos" icon={<CalendarDays/>}><MilestoneAgenda /></Panel>
  if (active === 'pendientes') return <Panel title="Acciones que requieren gestión" icon={<CheckCircle2/>}><PriorityActions limit={3}/></Panel>
  if (active === 'responsables') return <Panel title="Carga de acciones por responsable" icon={<UserRoundCheck/>}><ResponsibilityBars/></Panel>
  if (active === 'reporteria') return <ReportingDemo />
  return <AssistantDemo />
}
function Panel({title,icon,children}:{title:string;icon:ReactNode;children:ReactNode}){return <div className="product-panel"><PanelHead title={title} icon={icon}/>{children}</div>}
function PanelHead({title,icon}:{title:string;icon?:ReactNode}){return <div className="product-panel-head"><div>{icon}<div><small>Demo ilustrativa · Datos ficticios</small><h3>{title}</h3></div></div><span>Actualización demo · Esta semana</span></div>}
function Subhead({title,icon}:{title:string;icon:ReactNode}){return <div className="portfolio-subhead">{icon}<strong>{title}</strong></div>}
function PortfolioOverview(){return <div className="product-panel portfolio-overview"><PanelHead title="Estado del portafolio"/><div className="portfolio-kpis">{demoKpis.map(item=><article className={`portfolio-kpi tone-${item.tone}`} key={item.label}><span>{item.label}</span><strong>{item.value}</strong><small>{item.detail}</small></article>)}</div><div className="portfolio-chart-grid"><Distribution title="Distribución por estado" items={statusDistribution}/><Distribution title="Riesgo del portafolio" items={riskDistribution}/></div><div className="portfolio-main-grid"><section className="portfolio-subpanel"><Subhead icon={<AlertTriangle/>} title="Alertas críticas"/><AlertPanel limit={2}/></section><section className="portfolio-subpanel"><Subhead icon={<CheckCircle2/>} title="Acciones prioritarias"/><PriorityActions limit={2}/></section></div></div>}
function Distribution({title,items}:{title:string;items:typeof statusDistribution}){return <section className="distribution-card"><strong>{title}</strong><div className="distribution-track">{items.map(item=><i key={item.label} style={{width:`${item.percent}%`,background:item.color}}/>)}</div><div className="distribution-legend">{items.map(item=><span key={item.label}><i style={{background:item.color}}/>{item.label}<b>{item.value}</b></span>)}</div></section>}
function AlertPanel({limit}:{limit:number}){return <div className="alert-list">{demoAlerts.slice(0,limit).map((alert,index)=><article className={`alert-row${index?' follow':''}`} key={alert.title}><div><strong>{alert.title}</strong><span>{alert.project} · {alert.situation}</span><p>Pendiente: {alert.pending} · Responsable: {alert.owner}</p></div><div className="risk-block"><span>▲ {alert.risk}</span><strong>{alert.days}</strong><small>días</small></div></article>)}</div>}
function PriorityActions({limit}:{limit:number}){return <div className="priority-list">{demoActions.slice(0,limit).map(action=><article className="priority-card" key={action.rank}><span>{action.rank} · {action.level}</span><h4>{action.project}</h4><p>{action.summary}</p><div className="priority-meta"><small>Responsable <b>{action.owner}</b></small><small>Plazo <b>{action.due}</b></small><small>Estado <b>{action.state}</b></small></div></article>)}</div>}
function PermitRegister(){return <div className="register-table"><div className="register-row register-head">{labels.map(x=><span key={x}>{x}</span>)}</div>{permitRows.map(row=><div className="register-row" key={row[0]}>{row.map((cell,i)=><span data-label={labels[i]} key={labels[i]}>{i===3?<><i className="progress-mini"><b style={{width:cell}}/></i>{cell}</>:cell}</span>)}</div>)}</div>}
function MilestoneAgenda(){return <div className="milestone-agenda">{milestones.map(item=><article className={`milestone-item status-${item.status.toLowerCase()}`} key={`${item.date}-${item.project}`}><time>{item.date}</time><div><span>{item.project}</span><strong>{item.milestone}</strong><small>Dependencia: {item.dependency}</small></div><div><b>{item.days}</b><span>{item.status}</span><small>{item.owner}</small></div></article>)}</div>}
function ResponsibilityBars(){return <div className="responsibility-panel"><div className="responsibility-bars">{responsibilityLoad.map(item=><div className="responsibility-row" key={item.label}><span>{item.label}</span><i><b style={{width:`${item.width}%`}}/></i><strong>{item.value}</strong><small>{item.overdue} venc. · {item.critical} crít.</small></div>)}</div><div className="owner-summary"><span>15</span><strong>acciones abiertas</strong><p>5 vencidas y 3 críticas distribuidas entre responsables.</p></div></div>}
function ReportingDemo(){return <div className="product-panel report-panel"><PanelHead title="Reportería ejecutiva" icon={<FileText/>}/><div className="report-preview"><article className="pdf-preview"><div className="preview-toolbar"><FileText/><span>RESUMEN_EJECUTIVO_DEMO.pdf</span><b>1 / 3</b></div><div className="pdf-sheet"><small>ALEN CONTROL · INFORME SEMANAL</small><h4>Estado ejecutivo del portafolio</h4><div>{demoKpis.slice(0,4).map(k=><span key={k.label}>{k.label}<b>{k.value}</b></span>)}</div><p>Foco de gestión: resolver antecedentes críticos, confirmar responsables y proteger los próximos hitos.</p></div></article><article className="email-preview"><div className="preview-toolbar"><Mail/><span>Correo ejecutivo</span><b>Borrador</b></div><dl><dt>Para</dt><dd>Comité de proyecto</dd><dt>Asunto</dt><dd>Resumen semanal · decisiones requeridas</dd></dl><p>Esta semana, <strong>6 proyectos requieren atención</strong>. Se proponen tres decisiones prioritarias:</p><ol><li>Destrabar firma de expediente.</li><li>Validar documentación de hito.</li><li>Confirmar respuesta sectorial.</li></ol></article></div></div>}
export function AssistantDemo(){const [selected,setSelected]=useState(0);const active=assistantQuestions[selected];return <div className="product-panel assistant-panel"><PanelHead title="Inteligencia que complementa la experiencia" icon={<Sparkles/>}/><p className="assistant-principle">Consulta guiada sobre los datos demo. La tecnología apoya; el criterio profesional decide.</p><div className="assistant-workspace"><div className="assistant-prompts">{assistantQuestions.map((item,index)=><button className={selected===index?'is-selected':''} type="button" onClick={()=>setSelected(index)} key={item.question}>{item.question}</button>)}</div><div className="assistant-answer" aria-live="polite"><span>Respuesta asistida</span><strong>{active.question}</strong><p>{active.answer}</p><small>Fuente: datos demostrativos del portafolio · Validar antes de decidir.</small></div></div></div>}
